### ISSUE TITLE
Access to audit log for non-admin users

### ISSUE THREAD

**Issue by edwinvanelk** [mendix/AuditTrailModule#21]
We would like to give a user without an Administrator role the possibility to view audit trail info. In our sample app project user role "User" does not have the AuditTrail.MxAdministrator role, but (only) module role "BasicRightsAudittrail".

Trying to use snippet AuditTrail.LogOverviewSnippet on Home_User page gives:
Executing action failed for security reasons: DSO_ToggleUI Error: Executing action failed for security reasons: DSO_ToggleUI

We do not want to give the non-admin user the module role MxAdministrator (because module role MxAdministrator has also delete rights for several entities, etc.)

Proposed changes:

* make MF DSO_ToggleUI available for role "BasicRightsAudittrail" too
* make MF OCl_ToggleUI available for role "BasicRightsAudittrail" too
* give NP entity AuditTrail.UIToggle read access for role "BasicRightsAudittrail"
* make page LogLine_View available for role "BasicRightsAudittrail"

Edwin van Elk
Ordina DS

**Comment by dahfjkg** [comment]
We addressed this issue in the following versions of the module: 8.1.1 for Mendix 8 and 9.0.1 for Mendix 9
