### ISSUE TITLE
no tag for the released 9.0.1 package

### ISSUE THREAD

**Issue by Nuno-RC** [mendix/AuditTrailModule#30]
Hello, 
A 9.0.1 release of this module as been created the 8th April 2022.
![image](https://user-images.githubusercontent.com/90385050/175393900-a0a98277-26d7-4d11-8c43-11c6997e9ae5.png)

But I did not see its associated source code in the Github repo ( No tag ).

So my company refuses to use It.

can you please create the right tag ?

Thanks

**Comment by Nuno-RC** [comment]
I just saw the tag has been created.
Thanks.

**Comment by passalaqua** [comment]
Hello @Nuno-RC,

Thank you for bringing this up. We had indeed not tagged and created a release in github for these patch releases. As you saw, this has been fixed and you should be able to find both v8.1.1 and v9.0.1 in the release page now (https://github.com/mendix/AuditTrailModule/releases).

However, please be aware that this is a manual step for which we provide no guarantees. It is not recommended to rely on having a release in github for modules published in the Mendix Marketplace.

Kind regards
