### ISSUE TITLE
Enable Store 'createdDate' and the others for AudittrailSuperClass

### ISSUE THREAD

**Issue by basi01** [mendix/AuditTrailModule#31]
Please enable `Store 'createdDate'` and the others for `AudittrailSuperClass`. The module users are not allowed to do that in their specializations. See System.FileDocument as an example. These 4 system attributes are enabled there for a reason.

**Comment by dahfjkg** [comment]
Greetings!

This is a good idea, but adding system fields to the supetentity will affect all users of the module.
Please consider using the other approach (see [Associations and Events]( https://docs.mendix.com/appstore/modules/audit-trail/#21-associations-and-events)). That should give you more flexibility in regard to system fields.
