### ISSUE TITLE
Suggestion for date localization

### ISSUE THREAD

**Issue by hello-mendix-world** [mendix/AuditTrailModule#36]
![2022-12-15 11_07_07-Mendix - Homepage](https://user-images.githubusercontent.com/63280831/207831893-28ab83c2-6d39-46cf-a975-165a06c66e76.png)

When a log object is created, a date attribute is set in two places:
1) **Log.DateTime** is shown on **LogOverviewSnippet** but is not localized, you see the UTC date. I would suggest localize this in the data model (or add UTC as a description in the snippet).
2) **Log.Description** has a value 'UTC' appended at the end but I think this one is obsolete, since this is the localized date.

In my case, this result in incorrect/unclear dates in the **LogOverviewSnippet**.

**Comment by dahfjkg** [comment]
We addressed incorrect handling of local time in the latest release of the module: 8.1.2 for Mendix 8 and 9.0.2 for Mendix 9
