### ISSUE TITLE
Audit trail on account, log deletes when only changed attributes are logged.

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/AuditTrailModule#4]
When using auditing on Account, the logic gets confused. If user Admin changes user NormalUser, it would appear in the audit trail that NormalUser made the change.

We log only changed attributes. In that situation, deletes go unnoticed because there are no changed attributes. With debug logging, log message _No log lines created (no attributes changed),_ appears.

Also we want to log when the user's time zone or language changes.

I attached a changed file. Just search for Marcel

[CreateLogObject.zip](https://github.com/mendix/AuditTrailModule/files/1663427/CreateLogObject.zip)

**Comment by pouyaist** [comment]
It is fixed
