### ISSUE TITLE
Improve logging of references - do not log full referenced object

### ISSUE THREAD

**Issue by ivosturm** [mendix/AuditTrailModule#6]
In my opinion it does not make sense to log an associated object with all it's members. This is clogging up the database unnecessarily. An option I implemented for this is to per AuditTrailSuperClass specialisation, populate an extra to be created attribute in the ModelReflection.MxObjectReference called KeyAttribute. 
Only show this KeyAttribute to the user if a LogLine for a reference is shown.

**Comment by jacobdehorn** [comment]
I face the same challenge. Can you show me how you worked around this?

**Comment by passalaqua** [comment]
Hi @ivosturm ,

We recently released a new version of the Audit Trail (v7.5.0) that significantly improves the logging of references and reference sets. While it still logs attributes of references, it no longer does so as a single text field in the log line entity and it is now possible to filter which references have been unchanged, added or deleted. We believe this already significantly reduces the number of logged objects.

Please try this new version, and feel free to open a new issue if you believe this to be insufficient.
