### ISSUE TITLE
Loggin of reference (set) - readable old/new values

### ISSUE THREAD

**Issue by jacobdehorn** [mendix/AuditTrailModule#7]
When the java-action creates a logline for a reference or reference set, all information about the referenced object is copied to the new/old values string which makes it quite unreadable. 

Is there a way to only see one attribute/member in de new/old values instead of all? 
I read something about using the Model Reflection module (#6 ), but I don't know how I have to do this.

**Comment by passalaqua** [comment]
Hi @jacobdehorn ,

We just released a new version (v7.5.0) of the Audit Trail module which contains many improvements to logging references and reference sets. We now use a structured approach to avoid repeating unchanged values and making it clear which references have been added and which have been removed.

While it still logs all attributes of these references, it already makes viewing, filtering and searching for references of audited objects much easier. I will close this issue and assume this version solves your problem.
