### ISSUE TITLE
Improve logging of references (don't repeat MendixIdentifier/entityID/entityID)

### ISSUE THREAD

**Issue by MxSinan** [mendix/AuditTrailModule#8]
When having references in oldvalues/newvalues, there are some words/tags
repeated over and over again.

MendixIdentifier / entityID / entityID

Takes significant space when you have many references and Many objects.

**Comment by passalaqua** [comment]
Hi @MxSinan,

We just released a new version (v7.5.0) of the Audit Trail module which contains many improvements to logging references and reference sets. We now use a structured approach to avoid repeating unchanged values and making it clear which references have been added and which have been removed.

I will close this issue and assume this version solves your problem.
